package com.exmple.testing.tests;// Generated by Selenium IDE

import com.exmple.testing.model.AccountData;
import com.exmple.testing.model.CommentData;
import com.exmple.testing.model.PostData;
import org.junit.Test;

public class WebSiteTest extends TestBase {

    @Test
    public void writeComment() throws InterruptedException {
        app.window().setDimension(1296, 696);
        app.navigation().openSignInPage();
        app.auth().login(new AccountData("test@mail.ru", "123"));
        app.navigation().openBlogPage();
        app.comments().clickWriteComment();
        app.comments().writeComment(new CommentData("2323"));
    }

    @Test
    public void createPost() throws InterruptedException {
        app.window().setDimension(1296, 696);
        app.navigation().openSignInPage();
        app.auth().login(new AccountData("test@mail.ru", "123"));
        app.navigation().openBlogPage();
        app.posts().clickCreatePost();
        app.posts().createPost(new PostData("# ASD"));
    }

}
