package com.exmple.tests;// Generated by Selenium IDE

import org.junit.Test;

public class WebSiteTest extends TestBase {

    @Test
    public void writeComment() throws InterruptedException {
        openSignInPage();
        login(new AccountData("test@mail.ru", "123"));
        openBlogPage();
        super.writeComment();
    }

    @Test
    public void createPost() throws InterruptedException {
        openSignInPage();
        login(new AccountData("test@mail.ru", "123"));
        openBlogPage();
        clickCreatePost();
        createPost(new PostData("# ASD"));
    }

}
